version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    restart: always
    ports:
      - "8080:8080"   # Puerto de Jenkins
      - "50000:50000" # Puerto para agentes Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistencia de datos de Jenkins
      - /var/run/docker.sock:/var/run/docker.sock # Para que Jenkins pueda usar Docker

volumes:
  jenkins_home: